service: my-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  environment:
    DB_HOST: mydb.cc7dergrgvwi.us-east-2.rds.amazonaws.com
    DB_USER: admin
    DB_PASSWORD: Naveen2628
    DB_NAME: configurator
functions:
  app:
    handler: app.handler
    events:
      - httpApi:
          path: /{any+}
          method: "*"
